apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-mhib
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-mhib@sha256:dbaf0bc355f2ad64405f1a670f021cb88f23235c22417788f34e613b3c2d4334
        name: my-nodejs
        resources: {}
status: {}
